import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";
import Cart from "@/components/Cart";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shop Luvra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  font-sans text-black `}
      >
        <div className="relative z-10">
          <Nav />
          <Menu />
          <main className="flex-1  bg-white pt-32 px-5 sm:px-10 lg:px-5 ">
            {children}
            <Toaster position="top-right" />
          </main>
          <Cart />
        </div>
        <div className="sticky bottom-0  z-0 ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
